# POC Pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: k6-load-test@0
  inputs: 
    args: -e ENVIRONMENT=$(Environment)
    filename: 'tests/noTechMetadataTest.js & tests/techMetadataTest.js' 

